/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mask.hrs.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-17-2011
 * 
 * XDoclet definition:
 * @struts.form name="loactionSearchForm"
 */
public class LoactionSearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** child_age_2 property */
	private String child_age_2;

	/** child_type_6 property */
	private String child_type_6;

	/** leftTime property */
	private String leftTime;

	/** adults property */
	private String adults;

	/** child_age_1 property */
	private String child_age_1;

	/** destiny property */
	private String destiny;

	/** comeTime property */
	private String comeTime;

	/** singleRooms property */
	private String singleRooms;

	/** child_age_4 property */
	private String child_age_4;

	/** doubleRooms property */
	private String doubleRooms;

	/** minRating property */
	private String minRating;

	/** child_type_3 property */
	private String child_type_3;

	/** child_age_6 property */
	private String child_age_6;

	/** hotelName property */
	private String hotelName;

	/** child_type_2 property */
	private String child_type_2;

	/** child_age_5 property */
	private String child_age_5;

	/** child_type_4 property */
	private String child_type_4;

	/** child_age_3 property */
	private String child_age_3;

	/** child_type_1 property */
	private String child_type_1;

	/** children property */
	private String children;

	/** maxprice property */
	private String maxprice;

	/** child_type_5 property */
	private String child_type_5;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the child_age_2.
	 * @return String
	 */
	public String getChild_age_2() {
		return child_age_2;
	}

	/** 
	 * Set the child_age_2.
	 * @param child_age_2 The child_age_2 to set
	 */
	public void setChild_age_2(String child_age_2) {
		this.child_age_2 = child_age_2;
	}

	/** 
	 * Returns the child_type_6.
	 * @return String
	 */
	public String getChild_type_6() {
		return child_type_6;
	}

	/** 
	 * Set the child_type_6.
	 * @param child_type_6 The child_type_6 to set
	 */
	public void setChild_type_6(String child_type_6) {
		this.child_type_6 = child_type_6;
	}

	/** 
	 * Returns the leftTime.
	 * @return String
	 */
	public String getLeftTime() {
		return leftTime;
	}

	/** 
	 * Set the leftTime.
	 * @param leftTime The leftTime to set
	 */
	public void setLeftTime(String leftTime) {
		this.leftTime = leftTime;
	}

	/** 
	 * Returns the adults.
	 * @return String
	 */
	public String getAdults() {
		return adults;
	}

	/** 
	 * Set the adults.
	 * @param adults The adults to set
	 */
	public void setAdults(String adults) {
		this.adults = adults;
	}

	/** 
	 * Returns the child_age_1.
	 * @return String
	 */
	public String getChild_age_1() {
		return child_age_1;
	}

	/** 
	 * Set the child_age_1.
	 * @param child_age_1 The child_age_1 to set
	 */
	public void setChild_age_1(String child_age_1) {
		this.child_age_1 = child_age_1;
	}

	/** 
	 * Returns the destiny.
	 * @return String
	 */
	public String getDestiny() {
		return destiny;
	}

	/** 
	 * Set the destiny.
	 * @param destiny The destiny to set
	 */
	public void setDestiny(String destiny) {
		this.destiny = destiny;
	}

	/** 
	 * Returns the comeTime.
	 * @return String
	 */
	public String getComeTime() {
		return comeTime;
	}

	/** 
	 * Set the comeTime.
	 * @param comeTime The comeTime to set
	 */
	public void setComeTime(String comeTime) {
		this.comeTime = comeTime;
	}

	/** 
	 * Returns the singleRooms.
	 * @return String
	 */
	public String getSingleRooms() {
		return singleRooms;
	}

	/** 
	 * Set the singleRooms.
	 * @param singleRooms The singleRooms to set
	 */
	public void setSingleRooms(String singleRooms) {
		this.singleRooms = singleRooms;
	}

	/** 
	 * Returns the child_age_4.
	 * @return String
	 */
	public String getChild_age_4() {
		return child_age_4;
	}

	/** 
	 * Set the child_age_4.
	 * @param child_age_4 The child_age_4 to set
	 */
	public void setChild_age_4(String child_age_4) {
		this.child_age_4 = child_age_4;
	}

	/** 
	 * Returns the doubleRooms.
	 * @return String
	 */
	public String getDoubleRooms() {
		return doubleRooms;
	}

	/** 
	 * Set the doubleRooms.
	 * @param doubleRooms The doubleRooms to set
	 */
	public void setDoubleRooms(String doubleRooms) {
		this.doubleRooms = doubleRooms;
	}

	/** 
	 * Returns the minRating.
	 * @return String
	 */
	public String getMinRating() {
		return minRating;
	}

	/** 
	 * Set the minRating.
	 * @param minRating The minRating to set
	 */
	public void setMinRating(String minRating) {
		this.minRating = minRating;
	}

	/** 
	 * Returns the child_type_3.
	 * @return String
	 */
	public String getChild_type_3() {
		return child_type_3;
	}

	/** 
	 * Set the child_type_3.
	 * @param child_type_3 The child_type_3 to set
	 */
	public void setChild_type_3(String child_type_3) {
		this.child_type_3 = child_type_3;
	}

	/** 
	 * Returns the child_age_6.
	 * @return String
	 */
	public String getChild_age_6() {
		return child_age_6;
	}

	/** 
	 * Set the child_age_6.
	 * @param child_age_6 The child_age_6 to set
	 */
	public void setChild_age_6(String child_age_6) {
		this.child_age_6 = child_age_6;
	}

	/** 
	 * Returns the hotelName.
	 * @return String
	 */
	public String getHotelName() {
		return hotelName;
	}

	/** 
	 * Set the hotelName.
	 * @param hotelName The hotelName to set
	 */
	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	/** 
	 * Returns the child_type_2.
	 * @return String
	 */
	public String getChild_type_2() {
		return child_type_2;
	}

	/** 
	 * Set the child_type_2.
	 * @param child_type_2 The child_type_2 to set
	 */
	public void setChild_type_2(String child_type_2) {
		this.child_type_2 = child_type_2;
	}

	/** 
	 * Returns the child_age_5.
	 * @return String
	 */
	public String getChild_age_5() {
		return child_age_5;
	}

	/** 
	 * Set the child_age_5.
	 * @param child_age_5 The child_age_5 to set
	 */
	public void setChild_age_5(String child_age_5) {
		this.child_age_5 = child_age_5;
	}

	/** 
	 * Returns the child_type_4.
	 * @return String
	 */
	public String getChild_type_4() {
		return child_type_4;
	}

	/** 
	 * Set the child_type_4.
	 * @param child_type_4 The child_type_4 to set
	 */
	public void setChild_type_4(String child_type_4) {
		this.child_type_4 = child_type_4;
	}

	/** 
	 * Returns the child_age_3.
	 * @return String
	 */
	public String getChild_age_3() {
		return child_age_3;
	}

	/** 
	 * Set the child_age_3.
	 * @param child_age_3 The child_age_3 to set
	 */
	public void setChild_age_3(String child_age_3) {
		this.child_age_3 = child_age_3;
	}

	/** 
	 * Returns the child_type_1.
	 * @return String
	 */
	public String getChild_type_1() {
		return child_type_1;
	}

	/** 
	 * Set the child_type_1.
	 * @param child_type_1 The child_type_1 to set
	 */
	public void setChild_type_1(String child_type_1) {
		this.child_type_1 = child_type_1;
	}

	/** 
	 * Returns the children.
	 * @return String
	 */
	public String getChildren() {
		return children;
	}

	/** 
	 * Set the children.
	 * @param children The children to set
	 */
	public void setChildren(String children) {
		this.children = children;
	}

	/** 
	 * Returns the maxprice.
	 * @return String
	 */
	public String getMaxprice() {
		return maxprice;
	}

	/** 
	 * Set the maxprice.
	 * @param maxprice The maxprice to set
	 */
	public void setMaxprice(String maxprice) {
		this.maxprice = maxprice;
	}

	/** 
	 * Returns the child_type_5.
	 * @return String
	 */
	public String getChild_type_5() {
		return child_type_5;
	}

	/** 
	 * Set the child_type_5.
	 * @param child_type_5 The child_type_5 to set
	 */
	public void setChild_type_5(String child_type_5) {
		this.child_type_5 = child_type_5;
	}
}