/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mask.reservation.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-29-2010
 * 
 * XDoclet definition:
 * @struts.form name="reservationForm"
 */
public class ReservationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** double_room property */
	private String double_room;

	/** single_room property */
	private String single_room;

	/** custom_tel property */
	private String custom_tel;

	/** custom_name property */
	private String custom_name;

	/** custom_email property */
	private String custom_email;

	/** reservation_type property */
	private String reservation_type;

	/** left_time property */
	private String left_time;

	/** come_time property */
	private String come_time;

	/** hotel_id property */
	private String hotel_id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the double_room.
	 * @return String
	 */
	public String getDouble_room() {
		return double_room;
	}

	/** 
	 * Set the double_room.
	 * @param double_room The double_room to set
	 */
	public void setDouble_room(String double_room) {
		this.double_room = double_room;
	}

	/** 
	 * Returns the single_room.
	 * @return String
	 */
	public String getSingle_room() {
		return single_room;
	}

	/** 
	 * Set the single_room.
	 * @param single_room The single_room to set
	 */
	public void setSingle_room(String single_room) {
		this.single_room = single_room;
	}

	/** 
	 * Returns the custom_tel.
	 * @return String
	 */
	public String getCustom_tel() {
		return custom_tel;
	}

	/** 
	 * Set the custom_tel.
	 * @param custom_tel The custom_tel to set
	 */
	public void setCustom_tel(String custom_tel) {
		this.custom_tel = custom_tel;
	}

	/** 
	 * Returns the custom_name.
	 * @return String
	 */
	public String getCustom_name() {
		return custom_name;
	}

	/** 
	 * Set the custom_name.
	 * @param custom_name The custom_name to set
	 */
	public void setCustom_name(String custom_name) {
		this.custom_name = custom_name;
	}

	/** 
	 * Returns the custom_email.
	 * @return String
	 */
	public String getCustom_email() {
		return custom_email;
	}

	/** 
	 * Set the custom_email.
	 * @param custom_email The custom_email to set
	 */
	public void setCustom_email(String custom_email) {
		this.custom_email = custom_email;
	}

	/** 
	 * Returns the reservation_type.
	 * @return String
	 */
	public String getReservation_type() {
		return reservation_type;
	}

	/** 
	 * Set the reservation_type.
	 * @param reservation_type The reservation_type to set
	 */
	public void setReservation_type(String reservation_type) {
		this.reservation_type = reservation_type;
	}

	/** 
	 * Returns the left_time.
	 * @return String
	 */
	public String getLeft_time() {
		return left_time;
	}

	/** 
	 * Set the left_time.
	 * @param left_time The left_time to set
	 */
	public void setLeft_time(String left_time) {
		this.left_time = left_time;
	}

	/** 
	 * Returns the come_time.
	 * @return String
	 */
	public String getCome_time() {
		return come_time;
	}

	/** 
	 * Set the come_time.
	 * @param come_time The come_time to set
	 */
	public void setCome_time(String come_time) {
		this.come_time = come_time;
	}

	/** 
	 * Returns the hotel_id.
	 * @return String
	 */
	public String getHotel_id() {
		return hotel_id;
	}

	/** 
	 * Set the hotel_id.
	 * @param hotel_id The hotel_id to set
	 */
	public void setHotel_id(String hotel_id) {
		this.hotel_id = hotel_id;
	}
}